<a href="https://colab.research.google.com/github/kangtaeksu/Trio/blob/main/pandas_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import
import pandas as pd

# Series 객체 만들기
data = ['2016', '2017', '2018', '2019']
result = pd.Series(data)
print(result)

print("##############################")
print(result.index) # 모든 index값 출력
print(result.values) # 모든 데이터값 출력

# Series 객체 이름 지정하기(이름 기반 데이터 이해)
print("##############################")
result.name = 'Year'
print(result)

# Series 객체의 인덱스명 지정
print("##############################")
result.index.name = 'No'
print(result)

# index 지정해 Series 객체 생성
print("##############################")
data = ['2016', '2017', '2018', '2019']
result = pd.Series(data, index=['a','b','c','d'])
print(result)
print(result.index)

# dictionary 이용해 Series 객체 생성하기, Key가 Index 되고 Value가 값이 된다.
print("##############################")
score = {'Kim' : 85, 'Hwang' : 100, 'Lee' : 99, 'Choi' : 80}
result = pd.Series(score)
print(result)
print(result.index)
print(result.values)

# Series 내 Value 값 접근하기(Index)
print("##############################")
print(result['Lee'])
print(result['Hwang'])

# 연산 진행하기
print("##############################")
data = pd.Series([1, -1, 3, 5])
print(data)
print(data+100)

0    2016
1    2017
2    2018
3    2019
dtype: object
##############################
RangeIndex(start=0, stop=4, step=1)
['2016' '2017' '2018' '2019']
##############################
0    2016
1    2017
2    2018
3    2019
Name: Year, dtype: object
##############################
No
0    2016
1    2017
2    2018
3    2019
Name: Year, dtype: object
##############################
a    2016
b    2017
c    2018
d    2019
dtype: object
Index(['a', 'b', 'c', 'd'], dtype='object')
##############################
Kim       85
Hwang    100
Lee       99
Choi      80
dtype: int64
Index(['Kim', 'Hwang', 'Lee', 'Choi'], dtype='object')
[ 85 100  99  80]
99
100
0    1
1   -1
2    3
3    5
dtype: int64
0    101
1     99
2    103
3    105
dtype: int64

In [ ]:
import pandas as pd
import numpy as np
# Data Frame 생성하기
data = { 'name' : ['Lee', 'Hwang', 'Kim', 'Choi'],
        'score' : [100, 95, 90, 85],
        'grade' : ['A', 'A', 'B', 'B']}

df = pd.DataFrame(data)
print(df)
print(df.index) # 객체의 인덱스 뽑기
print(df.columns) # Index라고 명시되어 출력되나 실제는 column데이터
print(df.values) # Index를 제거한 Frame 내부의 값만 출력됨(리스트 형태)

# DataFrame 객체의 index, column 명 지정
print("##############################")
df.index.name = 'No'
df.columns.name = 'Info'
print(df)

# DataFrame 컬럼 추가하여 새로 생성해보기
# etc 컬럼이 추가되어 NaN(Not a Number) 데이터를 갖는 열이 추가됨
print("##############################")
c = ['name', 'grade', 'score', 'etc']
df2 = pd.DataFrame(data, columns = c)
print(df2)

# 새로운 행/열 추가 시 지정 값 없으면 NaN이 된다.
# 아래에서 Woo는 score에 없으므로 index Woo의 값은 NaN이 된다.
print("##############################")
score = {'Kim' : 85, 'Hwang' : 100, 'Lee':99, 'Choi':80}
students = ['Hwang', 'Lee', 'Woo']
result = pd.Series(score, index=students)
print(result)

# DataFrame의 Shape
print("##############################")
print(df2.shape) # DataFrame의 Shape은 Index/Columns는 포함하지 않음

# DataFrame의 간단한 정보 확인하기
# etc는 0 non-null 즉, 전체 값이 결측치라는 의미이다.
print("##############################")
print(df2.info())

# head(n) : 최상위 n행의 데이터를 읽음
# tail(n) : 최하위 n행의 데이터를 읽음
# n을 전달하지 않으면 default 값인 5개 행이 보임
print("##############################")
print(df.head(2))
print(df.tail(2))

# 인덱싱
# 기존 배열들의 인덱싱을 그대로 사용할 수 있음
print("##############################")
print(df['name']) # column 명 기반 인덱싱
print(df[['name', 'grade', 'score']]) # 복수 column 데이터 접근

df2['etc'] = [11, 22, 33, 44] # 특정 column의 값을 지정해 변경
print(df2)
df2['etc'] = 0 # etc columns의 모든 값을 0으로 변경

df2['etc'] = np.zeros(4) # numpy함수를 이용해서 변경도 가능

# Series  객체 이용해 Column 데이터 추가하기
print("##############################")
points = pd.Series([1.5, 1.7, 2.4], index=[0, 1, 2])
df2['points'] = points  # 기존에 index 없었어도 호출하여 데이터 입력 가능
print(df2) # 값이 3개여서 나머지 하나는 NaN으로 저장됨

# 연산을 통해 Column 데이터 추가
print("##############################")
df2['high_score'] = df2['score'] > 90
print(df2)

# loc(행 조건, 열 조건) 함수를 통해 Row 데이터 추가하기
# 4번째 행의 모든 열의 값을 아래와 같이 추가
print("##############################")
df2.loc[4, :] = ['Su', 70, 'C', 0.0, 1.1, False]
print(df2)

# del 명령어로 Column 데이터 삭제
print("##############################")
del df2['etc']
print(df2)

# drop 함수를 통해 Row 데이터 삭제해보기
# 원본 데이터에는 영향이 없고 새로운 객체를 반환한다.
print("##############################")
print(df2.drop(4))
df2.drop(4, inplace=True) # 만약 inplace=True를 하면 원본을 변경함

# 데이터 조회하기
# set_index(keys='column') 함수를 이용해 인덱스 변경
print("##############################")
df2.set_index('name', inplace=True) # index를 name column으로 변경
print(df2)

# Slicing하여 Row 조회하기 : []안에 슬라이싱 정보[start:end]로 조회
print("##############################")
print(df2[1:3])
print(df2[:2])

# loc[Row조건식, (Column 조건식)] 으로 데이터 조회
print("##############################")
print(df2.loc['Lee'])
print(df2.loc[['Lee', 'Choi']]) # 리스트로 구성해 복수 데이터 조회
print(df2.loc[:'Kim']) # Kim이 End 값인데 End값 포함해서 출력됨, Index가 아니라 실제 data를 넣었기 때문
print(df2.loc['Kim':'Choi', ['grade', 'high_score']])

# iloc[Row 조건식, (Column 조건식)] 함수로 데이터 조회
print("##############################")
print(df2.iloc[0:3]) # df2[0:3]과 동일
print(df2.iloc[0:3, 1:3])

# Boolean Indexing을 활용해 데이터 조회
print("##############################")
# 예) 행 조건 : points가 1.5 초과, 열 조건 : all
print(df2.loc[df2['points'] > 1.5, : ])
# 예2) 행 조건 : grade가 A, 열 조건 : all
print(df2.loc[df2['grade'] == 'A', :])

# NaN 값 다루기
# NaN은 Not a Number로 null과 유사한 개념임
print("##############################")
df = pd.DataFrame(np.arange(18).reshape(6,3), 
                  index=['a', 'b', 'c', 'd', 'e', 'f'],
                  columns=['x', 'y', 'z'])
df['data1'] = pd.Series([1.7, 1.2, 2.4], index=['a', 'e', 'c'])
print(df)

# dropna() 함수 : 행 데이터 기준 NaN 값 포함된 데이터 제거 후 나머지를 DataFrame으로 반환
print(df.dropna(how='all')) # how='all'이면 전체 행 데이터가 NaN인 경우를 의미
print(df.dropna(how='any')) # 행 데이터 중 하나라도 NaN이면 drop

#################################
# NaN 값 다루기
print("##############################")
df = pd.DataFrame(np.arange(18).reshape(6,3), index=['a','b','c','d','e','f'],
                  columns=['x','y','z'])
df['data1'] = pd.Series([1.7, 1.2, 2.4], index=['a','e','c'])
df.loc['c'] = np.nan
print(df)
print(df.info())

# count() 함수 : 각 컬럼 별 누락값 제외한 데이터 수 반환하는 함수
print(df.count())

# isnull() 함수 : DataFrame내 NaN 데이터를 찾아 True, False 반환
print(df.isnull())

# dropna() 함수 : 행 데이터 기준 NaN 포함 데이터 조회/제거 후 나머지를 반환
# default how는 'any'
print(df.dropna()) # 'how 파라미터 값을 all 또는 any를 지정해 조건 지정가능
print(df) # inplace 값이 default False이므로 원본은 변화 없음
df.dropna(how='all', inplace=True)

print(df.dropna(axis=1)) # 행 아닌 컬럼기준으로 조회/제거
print(df.dropna(axis=1, how='all')) # 컬럼 전체가 NaN이면 삭제

# 데이터 수정
df.iloc[:2, 0] = np.nan
df.iloc[:4, 1] = np.nan
print(df)

# fillna() 함수 ; 누락 값을 다른 값으로 대체하는 함수
df.fillna(0) # 0으로 대체

# column 명을 통해 해당 컬럼만 대체 가능
df.fillna({'x' : 1, 'y':2}, inplace=True) # Dict 형태로 대체하고 원본 변경

print(df)

# 데이터 수정
df = pd.DataFrame(np.arange(18).reshape(6,3),
                  index=['a','e','h','d','c','f'],
                  columns=['x','y','z'])
df.loc['c'] = np.nan
print(df)

# DataFrame 정렬하기
# sort_index() 함수 : index 값을 기준으로 정렬함. default는 오름차순
print("##############################")
print(df.sort_index())
print(df.sort_index(ascending=False)) # 내림차순
print(df.sort_index(axis=1, ascending=False)) # 컬럼 index 기준 정렬

# sort_values(by='...') : 특정 컬럼 데이터 정렬 시 by옵션으로 컬럼명 지정
print(df.sort_values(by='x', ascending=False)) # 'x'가 정렬기준

# 집계함수 사용하기
print("##############################")
dates = pd.date_range('20200801', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), 
                  index=dates, columns=['A','B','C','D'])
print(df)

# mean(axis=) 평균 구하기
print(df.mean())
print(df.mean(1)) # Row 기준 평균

# 그룹 연산
# 내부 프로세스 진행 방식 : Split -> Apply -> Combine
# 전체 데이터를 그룹 별로 나누고, 그룹별 집계하여 하나로 합침
print("##############################")
df = pd.DataFrame({'product':['a','b','a','b','a','b','a','a'],
                   'sensor':['one','one','two','three','two','two','one','three'],
                   'x' : np.random.randn(8),
                   'y' : np.random.randn(8)})
print(df)

# groupby('그룹화할 대상') 함수 : 데이터 분석 시 사용됨(split)
grouped = df.groupby('product') # product가 a, b이므로 그에 따라 group화됨
print(grouped) # DataFrameGroupBy 객체가 반환됨

for key, value in grouped:
  print("---------------------")
  print("key :", key)
  print("value\n", value)

# Apply - sum()함수 : 덧셈연산 진행
print(df.groupby('product').sum()) # 덧셈은 숫자형태만 자동 적용

# 복수 컬럼으로 split 해보기
print(df.groupby(['product', 'sensor']).sum())

# 특정 컬럼에만 집계 적용시키기(컬럼명 지정)
print(df.groupby(['product', 'sensor'])['x'].sum())

# Apply - size() 함수 : 각 그룹화된 데이터 셋의 개수 반환
# 각 집계된 그룹에 데이터가 균등하게 분포되어 있는지 알 수 있음
print(df.groupby(['product', 'sensor']).size())

# Apply - agg('lists of func') 함수 : 여러 집계 함수를 동시 적용함
print(df.groupby(['product', 'sensor'])['x'].agg(['sum', 'mean']))

# Apply - agg(dict of column - func) 로 컬럼별 다른 집계하기
print(df.groupby(['product', 'sensor']).agg({'x':'max', 'y':'min'}))

# 데이터 수정
df = pd.DataFrame({'product':['a','b','a','b','a','b','a','a'],
                   'sensor':['one','one','two','three','two','two','one','three'],
                   'x' : np.random.randn(8),
                   'y' : np.random.randn(8)})

# Combine - DataFrame 객체 연속으로 붙이기
# concat(결합할 객체) 함수 : 2개 이상 DataFrame 객체 결합
print("##############################")
print(pd.concat([df[:3], df[5:]])) # 인덱스 3, 4 누락

# 아래와 같이 하면 인덱스가 다시 0부터 순서대로 됨
print(pd.concat([df[:3], df[5:]], ignore_index=True)) # 결합 시 인덱스 재정렬

# 그러나 아래와 같이 하면 NaN 데이터가 생기게 됨(비추천)
print(pd.concat([df[:3], df[5:]], axis=1)) # 가로로 붙임(Column으로)

# Combine - 서로 다른 데이터 결합해보기
df1 = pd.DataFrame({'name': ['A', 'C'], 'result': ['pass', 'pass']})

df2 = pd.DataFrame({'name' : ['A', 'B', 'C', 'D'],
                    'subject': ['sub1', 'sub2', 'sub3', 'sub4'],
                    'score' : [95, 85, 75, 80]})
print(df1)
print(df2)

# merge(left=, right=, on=) 함수 : 2개 이상의 DataFrame을 DBMS join 방식 결합
print(pd.merge(df1, df2, on='name')) # name 기준 결합
print(pd.merge(df1, df2, how='outer', on='name')) # on 기준이되 없는 데이터 있으면 NaN 결합

# apply(func=, axis=0) 함수 활용 : 사용자가 작성한 함수를 DataFrame의 각 행/열에 적용해 한 번에 실행하는 기능
# 샘플 데이터 생성
df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])

# 샘플 함수
def printinfo(x):
  print(x.describe())

# apply lambda 식으로 데이터 가공
df.apply(printinfo, axis=0) # 행 방향으로 각 정보 describe
df.apply(printinfo, axis=1) # 열 방향으로 각 정보 describe

In [ ]:
# DataFrame 연습
base_data = {'name' : ['David', 'Roy', 'Tina', 'Kim'],
             'score' : [78, 64, 70, 62],
             'grade' : ['C','D','C','D']}
df_prac = pd.DataFrame(base_data)
print(df_prac)
print("Index : ", df_prac.index)
print("Columns : ", df_prac.columns)
print("Value : ", df_prac.values)

base_columns = ['name', 'score', 'grade', 'etc']
df_prac = pd.DataFrame(base_data, columns=base_columns)
print(df_prac)

# numpy 함수의 1로 변경하기
import numpy as np
df_prac['etc'] = np.ones(4)

    name  score grade
0  David     78     C
1    Roy     64     D
2   Tina     70     C
3    Kim     62     D
Index :  RangeIndex(start=0, stop=4, step=1)
Columns :  Index(['name', 'score', 'grade'], dtype='object')
Value :  [['David' 78 'C']
 ['Roy' 64 'D']
 ['Tina' 70 'C']
 ['Kim' 62 'D']]
    name  score grade  etc
0  David     78     C  NaN
1    Roy     64     D  NaN
2   Tina     70     C  NaN
3    Kim     62     D  NaN